# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5256836f1b7d8a2b136f140858896fdddea504cb302cbca7c52f60a658daff9738cb5740f04f2bfb12a8d6c42de424282738afaa2a3278f3280a232fa873a3a

test:
  secret_key_base: ab62b4a9dfd367e2e001b0432704e5835089d266d9efcd22bae7880b8365bddaccc51c406dffcefaeb540d8de256133538ba7adf6a9cca7e179ed7121728ac7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
